# Generated by Django 5.0.4 on 2024-05-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bname', models.CharField(max_length=250)),
                ('Bemail', models.CharField(max_length=250)),
                ('Bmob', models.CharField(max_length=250)),
                ('guests', models.CharField(max_length=250)),
            ],
        ),
    ]
